version: '3'
services:
  mobius:
    image: iotketi/mobius:latest
    container_name: mobius
    restart: always
    ports:
      - "7579:7579"
      - "5683:5683/udp"
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mobius
      - MYSQL_DATABASE=mobiusdb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mobius
      MYSQL_DATABASE: mobiusdb
      MYSQL_USER: mobius
      MYSQL_PASSWORD: mobius
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
